export const AUTH_USER = 'AUTH_USER';
export const AUTH_ERROR = 'AUTH_ERROR';

export const USER_PACKAGES_LOADING = 'USER_PACKAGES_LOADING';
export const USER_PACKAGES_SUCCESS = 'USER_PACKAGES_SUCCESS';
export const USER_PACKAGES_ERROR = 'USER_PACKAGES_ERROR';

export const USER_TESTS_LOADING = 'USER_TESTS_LOADING';
export const USER_TESTS_SUCCESS = 'USER_TESTS_SUCCESS';
export const USER_TESTS_ERROR = 'USER_TESTS_ERROR';

export const USER_TEST_LOADING = 'USER_TEST_LOADING';
export const USER_TEST_SUCCESS = 'USER_TEST_SUCCESS';
export const USER_TEST_ERROR = 'USER_TEST_ERROR';

export const USER_SUPPORT_LOADING = 'USER_TEST_LOADING';
export const USER_SUPPORT_SUCCESS = 'USER_TEST_SUCCESS';
export const USER_SUPPORT_ERROR = 'USER_TEST_ERROR';

export const TEST_ATTEMPT_SUCCESS = 'TEST_ATTEMPT_SUCCESS';
export const TEST_ATTEMPT_ERROR = 'TEST_ATTEMPT_ERROR';
export const TEST_ATTEMPT_UPDATE_SUCCESS = 'TEST_ATTEMPT_UPDATE_SUCCESS';
export const TEST_ATTEMPT_UPDATE_ERROR = 'TEST_ATTEMPT_UPDATE_ERROR';

export const TEST_RESULT_SUCCESS = 'TEST_RESULT_SUCCESS';
export const TEST_RESULT_ERROR = 'TEST_RESULT_ERROR';

export const TEST_ATTEMPT_DETAILS_SUCCESS = 'TEST_ATTEMPT_DETAILS_SUCCESS';
export const TEST_ATTEMPT_DETAILS_COLORING = 'TEST_ATTEMPT_DETAILS_COLORING';
export const TEST_ATTEMPT_DETAILS_ERROR = 'TEST_ATTEMPT_DETAILS_ERROR';
export const TEST_ATTEMPT_DETAILS_RESET = 'TEST_ATTEMPT_DETAILS_RESET';

export const TEST_QUESTION_BOOKMARK_SUCCESS = 'TEST_QUESTION_BOOKMARK_SUCCESS';
export const TEST_QUESTION_BOOKMARK_ERROR = 'TEST_QUESTION_BOOKMARK_ERROR';

export const USER_QUESTIONS = 'USER_QUESTIONS';
export const USER_QUESTIONS_INCREASE_UPDATE = 'USER_QUESTIONS_INCREASE_UPDATE';
export const USER_QUESTIONS_DECREASE_UPDATE = 'USER_QUESTIONS_DECREASE_UPDATE';
export const USER_QUESTIONS_ERROR = 'USER_QUESTIONS_ERROR';

export const TEST_QUESTION_LOADING = 'TEST_QUESTION_LOADING';
export const TEST_QUESTION = 'TEST_QUESTION';
export const TEST_QUESTION_ERROR = 'TEST_QUESTION_ERROR';

export const ADD_CART_LOADING = 'ADD_CART_LOADING';
export const ADD_CART_SUCCESS = 'ADD_CART_SUCCESS';
export const ADD_CART_ERROR = 'ADD_CART_ERROR';
export const CART_RESET = 'CART_RESET';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';

export const HOMEPAGE_GRAND_TESTS_SUCCESS = 'HOMEPAGE_GRAND_TESTS_SUCCESS';
export const HOMEPAGE_GRAND_TESTS_ERROR = 'HOMEPAGE_GRAND_TESTS_ERROR';
